# global
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # ✅ Make sure proper MIME types are loaded
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile        on;
    keepalive_timeout  65;

    # ------------------------
    # SERVER 1 (app1)
    # ------------------------
    server {
        listen 80;
        server_name stopro.site;

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # ------------------------
    # SERVER 2 (app2)
    # ------------------------
    server {
        listen 80;
        server_name jky-harngmeas.store;
        root /var/www/jky-harngmeas.store;
        index index.html;

        location / {
            # proxy_pass http://127.0.0.1:8111;
            # proxy_set_header Host $host;
            # proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Forwarded-Proto $scheme;
            try_files $uri $uri/ /index.html;
        }
        # Static assets (js, css, images, fonts)
        location ~* \.(js|mjs|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
            try_files $uri =404;
            access_log off;
            expires 30d;
        }

    }

    # ------------------------
    # SERVER 3 (sovathapann.site, static Vite build)
    # ------------------------
    server {
        listen 80;
        server_name sovathapann.site www.sovathapann.site;

        root /var/www/sovathapann.site;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Static assets (js, css, images, fonts)
        location ~* \.(js|mjs|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
            try_files $uri =404;
            access_log off;
            expires 30d;
        }
    }
}